# Generated by Django 4.0.3 on 2022-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField()),
                ('nurse_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
