# Generated by Django 4.0.3 on 2022-03-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('dop', models.DateField()),
                ('user_id', models.IntegerField(max_length=8)),
                ('framework_version', models.DecimalField(decimal_places=2, max_digits=3)),
                ('software_version', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
